#!/usr/bin/env -S node --experimental-strip-types
// Reads src/taskpane/i18n/locales/en.json and writes
// src/taskpane/i18n/keys.generated.ts containing a TranslationKey
// literal-union type covering every leaf key.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SRC = resolve('src/taskpane/i18n/locales/en.json');
const OUT = resolve('src/taskpane/i18n/keys.generated.ts');

function flatten(obj: unknown, prefix = ''): string[] {
  if (typeof obj !== 'object' || obj === null) return [];
  const out: string[] = [];
  for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
    const path = prefix ? `${prefix}.${k}` : k;
    if (typeof v === 'string') out.push(path);
    else out.push(...flatten(v, path));
  }
  return out;
}

const json = JSON.parse(readFileSync(SRC, 'utf8'));
const keys = flatten(json).sort();

const body =
  '// AUTO-GENERATED by tools/gen-i18n-types.ts — do not edit by hand.\n' +
  '// Run `npm run gen:i18n` to regenerate.\n\n' +
  'export type TranslationKey =\n' +
  keys.map(k => `  | ${JSON.stringify(k)}`).join('\n') +
  ';\n';

writeFileSync(OUT, body);
console.log(`Wrote ${keys.length} keys to ${OUT}`);
